-- MySQL Script generated by MySQL Workbench
-- Tue Sep 30 15:32:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tienda2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda2` DEFAULT CHARACTER SET utf8 ;
USE `tienda2` ;

-- -----------------------------------------------------
-- Table `tienda2`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`categoria` (
  `id_categoria` INT(10) NOT NULL AUTO_INCREMENT,
  `nom_categoria` LONGTEXT NULL,
  `est_categoria` INT(1) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`marca` (
  `id_marca` INT(10) NOT NULL AUTO_INCREMENT,
  `nom_marca` LONGTEXT NULL,
  `marcacol` VARCHAR(45) NULL,
  `est_marca` INT(1) NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`producto` (
  `id_producto` INT(10) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(10) NOT NULL,
  `id_marca` INT(10) NOT NULL,
  `nom_producto` LONGTEXT NULL,
  `pc_producto` FLOAT(10,2) NULL,
  `pv_producto` FLOAT(10,2) NULL,
  `det_producto` LONGTEXT NULL,
  `est_producto` INT(1) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_producto_marca1_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tienda2`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_marca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `tienda2`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`cliente` (
  `id_cliente` INT(10) NOT NULL AUTO_INCREMENT,
  `nom_cliente` LONGTEXT NULL,
  `ap_cliente` LONGTEXT NULL,
  `am_cliente` LONGTEXT NULL,
  `ndoc_cliente` LONGTEXT NULL,
  `email_cliente` LONGTEXT NULL,
  `cel_cliente` LONGTEXT NULL,
  `dir_cliente` LONGTEXT NULL,
  `fn_cliente` DATE NULL,
  `user_cliente` LONGTEXT NULL,
  `pass_cliente` LONGTEXT NULL,
  `est_cliente` INT(1) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`usuario_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`usuario_tipo` (
  `idusuario_tipo` INT(10) NOT NULL AUTO_INCREMENT,
  `nom_usuario_tipo` LONGTEXT NULL,
  `est_usuario_tipo` INT(1) NULL,
  PRIMARY KEY (`idusuario_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`usuario` (
  `id_usuario` INT(10) NOT NULL AUTO_INCREMENT,
  `idusuario_tipo` INT(10) NOT NULL,
  `nom_usuario` LONGTEXT NULL,
  `ap_usuario` LONGTEXT NULL,
  `am_usuario` LONGTEXT NULL,
  `ndoc_usuario` LONGTEXT NULL,
  `email_usuario` LONGTEXT NULL,
  `cel_usuario` LONGTEXT NULL,
  `dir_usuario` LONGTEXT NULL,
  `fn_usuario` LONGTEXT NULL,
  `user_usuario` LONGTEXT NULL,
  `pass_usuario` VARCHAR(45) NULL,
  `est_usuario` INT(1) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_usuario_tipo1_idx` (`idusuario_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_usuario_tipo1`
    FOREIGN KEY (`idusuario_tipo`)
    REFERENCES `tienda2`.`usuario_tipo` (`idusuario_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`venta` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fec_venta` DATETIME NULL,
  `det_venta` LONGTEXT NULL,
  `est_venta` INT(1) NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_venta_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_venta_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `tienda2`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda2`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`venta_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`venta_detalle` (
  `id_venta_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_venta` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cant_venta_detalle` FLOAT(10,2) NULL,
  `pv_venta_detalle` FLOAT(10,2) NULL,
  `total_venta_detalle` FLOAT(10,2) NULL,
  `est_venta_detalle` INT(1) NULL,
  PRIMARY KEY (`id_venta_detalle`),
  INDEX `fk_venta_detalle_venta1_idx` (`id_venta` ASC) VISIBLE,
  INDEX `fk_venta_detalle_producto1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_venta_detalle_venta1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `tienda2`.`venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_detalle_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tienda2`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`proveedor` (
  `id_proveedor` INT(10) NOT NULL AUTO_INCREMENT,
  `nom_proveedor` LONGTEXT NULL,
  `ruc_proveedor` LONGTEXT NULL,
  `cel_proveedor` LONGTEXT NULL,
  `email_proveedor` LONGTEXT NULL,
  `dir_proveedor` LONGTEXT NULL,
  `est_proveedor` INT(1) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`compra` (
  `id_compra` INT(10) NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT(10) NOT NULL,
  `id_usuario` INT NOT NULL,
  `fec_compra` DATETIME NULL,
  `det_compra` LONGTEXT NULL,
  `est_compra` INT(1) NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_proveedor1_idx` (`id_proveedor` ASC) VISIBLE,
  INDEX `fk_compra_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_compra_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `tienda2`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda2`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda2`.`compra_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`compra_detalle` (
  `id_compra_detalle` INT(10) NOT NULL AUTO_INCREMENT,
  `id_compra` INT(10) NOT NULL,
  `id_producto` INT(10) NOT NULL,
  `cant_compra_detalle` FLOAT(10,2) NULL,
  `pc_compra_detalle` FLOAT(10,2) NULL,
  `tot_compra_detalle` FLOAT(10,2) NULL,
  `est_compra_detalle` INT(1) NULL,
  PRIMARY KEY (`id_compra_detalle`),
  INDEX `fk_compra_detalle_compra1_idx` (`id_compra` ASC) VISIBLE,
  INDEX `fk_compra_detalle_producto1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_compra_detalle_compra1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `tienda2`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_detalle_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tienda2`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
